//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public string TypePost { get; set; }
        public string TypeCor { get; set; }
        public string Department { get; set; }
        public System.DateTime Expiration_date { get; set; }
    }
}
